options:
  filter_gain: 0.2

control:
    dsGainPos: 5.0
    lambda0Pos: 80.0
    lambda1Pos: 80.0
    # lambda0Pos max: 80.0
    # lambda1Pos: 80.0
    dsGainOri: 5.0
    lambda0Ori: 8
    lambda1Ori: 5
    # dsGainOri: 8.0
    # lambda0Ori: 12
    # lambda1Ori: 8

target:
    pos: [0.7, 0.0, 0.5]
    quat: [0.7071068, 0.0, 0.7071068,  0.0]
    # pos: [0.6, 0.0, 0.4]
    # quat: [0.0, -0.7071068, 0.7071068,  0.0]