options:
  filter_gain: 0.2

control:
    dsGainPos: 5.0
    lambda0Pos: 40.0
    lambda1Pos: 40.0
    # lambda0Pos: 100.0
    # lambda1Pos: 100.0
    # dsGainOri: 3.0
    # lambda0Ori: 5
    # lambda1Ori: 2.5
    dsGainOri: 4.0
    lambda0Ori: 6
    lambda1Ori: 6
    # dsGainOri: 8.0
    # lambda0Ori: 12
    # lambda1Ori: 8

target:
    pos: [0.7, 0.0, 0.5]
    quat: [0.7071068, 0.0, 0.7071068,  0.0]
    # pos: [0.0, 0.0, 1.6]
    # quat: [0.9962, 0.0, 0.0872, 0.0]